### PR TITLE
Upstream fixes

### PR DESCRIPTION
**Pull request by massey101**

### CODE REVIEW

**Comment by LongHairedHacker** [comment]
Thanks for the pull request, but some additional information would really help me review it.

First of all where does this JAYCAR display come from?
And is it really just a green tap with with different row/column start?
In any case your code is inconsistent as it uses `st7735_column_start = 0` and `st7735_row_start = 0` [here](https://github.com/LongHairedHacker/avr-st7735/blob/c7e56536bb517a5a9b5e803532fbc49afa5f91e0/st7735.c#L138),
but sets `st7735_column_start = 32` [there](https://github.com/LongHairedHacker/avr-st7735/blob/c7e56536bb517a5a9b5e803532fbc49afa5f91e0/st7735.c#L204).
Also you do not set anything for the inverted landscape mode, which might be correct, but still seems odd as the other displays set starts the same for the regular and the inverted modes.

Then what exactly do you mean by 'cut off bitmaps'?
I have a suspicion and your code would look correct for that at first glance, but I don't want to merge this without properly checking it.

Also [this](https://github.com/LongHairedHacker/avr-st7735/blob/c7e56536bb517a5a9b5e803532fbc49afa5f91e0/spi.c#L6) this is not funny and I won't have any of it in my codebase.

**Comment by massey101** [comment]
Hey, Thanks for the quick response.

the JAYCAR display comes from Jaycar. Unfortunately I don't have much more information than that and as far as I can tell no one on the internet really knows how to tell displays apart either.

The row/column situation is odd I agree, but that just appears to be the way my display works. I avoided setting any column/row starts in the init since it is dependent on screen orientation. I can change this to match the landscape orientation if you would like.

For the cut off bitmaps it simply clips a bitmap that goes off the screen rather than refusing to draw it at all. It works for me in both x and y, but yes a good check is a good idea.

For the final point, that definitely wasn't meant to be a part of the pull request at all, I shall promptly remove it.

EDIT: Here's a link to the display if that helps: https://www.jaycar.com.au/128x128-lcd-screen-module-for-arduino/p/XC4629

**Comment by massey101** [comment]
Ready for review again.

**Comment by LongHairedHacker** [comment]
That looks much better now.

I have one last tiny question: Why do set PB0 to output in `spi_init()` ?
It's not used anywhere else it the code, is it?

**Comment by massey101** [comment]
Sorry for the late reply,
No it's not used. I've removed it.

**Pull request merged**
